id: P010480
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:52:00.425194
source_metadata:
  id: bdr:W3CN7487
  title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་དུ་ཕྱིན་པ་བརྒྱད་སྟོང་པ།
  author: ''
  volumes:
    89266bb138d24f97b7363a23f004b4b1:
      image_group_id: I3CN7489
      title: ''
      volume_number: 1
      total_pages: 1164
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
