id: IB5AB2F97
legacy_id: P010480
ocr_import_info:
  bdrc_scan_id: W3CN7487
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T05:38:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:37:33.928157+00:00'
last_modified: 2022-09-03 23:38:26.098954
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7487
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7487
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་དུ་ཕྱིན་པ་བརྒྱད་སྟོང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6502894332311139
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I3CN7489:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7489
      total_pages: 1164
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7489.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6502894332311139
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
